# Generated by Django 4.1 on 2022-08-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(blank=True, upload_to='')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('matn', models.CharField(max_length=900)),
                ('oqildi', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qonun.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(blank=True, upload_to='')),
                ('matn', models.TextField(max_length=1000)),
                ('oqildi', models.PositiveIntegerField()),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qonun.mavzu')),
            ],
        ),
    ]
