# Generated by Django 4.1 on 2022-08-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qonun', '0002_alter_yangilik_matn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolim',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bolim',
            name='nom_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bolim',
            name='nom_uz_cyrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bolim',
            name='nom_uz_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='matn_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='matn_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='matn_uz_cyrl',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='matn_uz_latn',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='nom_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='nom_uz_cyrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dars',
            name='nom_uz_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mavzu',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mavzu',
            name='nom_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mavzu',
            name='nom_uz_cyrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mavzu',
            name='nom_uz_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='matn_en',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='matn_ru',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='matn_uz_cyrl',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='matn_uz_latn',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='nom_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='nom_uz_cyrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='nom_uz_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dars',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzu_darslari', to='qonun.mavzu'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to='Static/images/'),
        ),
    ]
