# Generated by Django 4.0.4 on 2022-08-24 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qonun', '0003_bolim_nom_en_bolim_nom_ru_bolim_nom_uz_cyrl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bolim',
            name='nom_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='dars',
            name='matn_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='dars',
            name='nom_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='mavzu',
            name='nom_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='matn_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='nom_uz_cyrl',
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to='rasmlar'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_matn', models.CharField(max_length=1000)),
                ('togri', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_variantlari', to='qonun.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='dars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dars_testlari', to='qonun.dars'),
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testlar_soni', models.PositiveIntegerField()),
                ('togrilar_soni', models.PositiveIntegerField()),
                ('foiz', models.CharField(max_length=100)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qonun.dars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_natijalari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
